### ISSUE TITLE
Papers subsection suggestion

### ISSUE THREAD

**Issue by ybayle** [ChristosChristofidis/awesome-deep-learning#78]
Hi,

Thanks for this great list!
I would suggest to create subsections in the papers list, like Image, Audio, Video, NN architecture,... that would make the list more readable.
For the audio part, I have made a repo there: https://github.com/ybayle/awesome-deep-learning-music, that you can link to.

P.S.: There is a little double `n` typo here: `Google - Sequence to Sequence Learning with Nneural Networks`

**Comment by ChristosChristofidis** [comment]
Hey bayle,

Glad that you liked it ! =)

This is a very good suggestion as a general refactoring of the list.. added the repo that you created to the list, interesting!
