### ISSUE TITLE
Obsolete link to : Deep Learning by Yoshua Bengio, Ian Goodfellow and Aaron Courville (05/07/2015)

### ISSUE THREAD

**Issue by Pavitrag** [ChristosChristofidis/awesome-deep-learning#96]
Under "free online books" section, link to: "Deep Learning by Yoshua Bengio, Ian Goodfellow and Aaron Courville (05/07/2015)" has changed.
The new link is  www.deeplearningbook.org.
Infact older link does point to the newer link but I thought its better to point this out.
Please change it if you will.

**Comment by ChristosChristofidis** [comment]
Done!
